- name: install nginx
  hosts: all
  vars:
    NGINX_PORT: 81
    HTML_SRC: templates/nginx/html/index.html.j2
    HTML_DEST: /usr/share/nginx/html/index.html

  tasks:
 
  # GET hostname
  - name: Get Hostname
    shell: hostname
    register: hostname

  # GET Date
  - name: Gate Date
    shell : date "+%Y/%m/%d %H:%M:%S"
    register: date

  # Modify index.html
  - name: Modify index.html
    template: src={{ HTML_SRC }} dest={{ HTML_DEST }}
    notify: restert nginx

  # Reboot Handler
  handlers:
    - name: restert nginx
      service: name=nginx state=restarted
